PetstagramWebsite/PetstagramWebsite/accounts/urls.py
from django.urls import path, include

from PetstagramWebsite.accounts.views import UserRegisterView, UserLoginView, UserLogoutView, \
    ProfileEditView, ProfileDetailsView, ProfileDeleteView

urlpatterns = [
    path('register/', UserRegisterView.as_view(), name='register'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('profile/<int:pk>/', include([
        path('', ProfileDetailsView.as_view(), name='profile-details'),
        path('edit/', ProfileEditView.as_view(), name='profile-edit'),
        path('delete/', ProfileDeleteView.as_view(), name='profile-delete'),
    ])),
]

PetstagramWebsite/PetstagramWebsite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('PetstagramWebsite.common.urls')),
    path('accounts/', include('PetstagramWebsite.accounts.urls')),
    path('pets/', include('PetstagramWebsite.pets.urls')),
    path('photos/', include('PetstagramWebsite.photos.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PetstagramWebsite/PetstagramWebsite/accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.core.validators import MinLengthValidator

from PetstagramWebsite.accounts.validators import only_letters_validator


class PetstagramUser(AbstractUser):
    email = models.EmailField(
        unique=True
    )

    first_name = models.CharField(
        max_length=30,
        validators=(
            MinLengthValidator(2),
            only_letters_validator,
        )
    )

    last_name = models.CharField(
        max_length=30,
        validators=(
            MinLengthValidator(2),
            only_letters_validator,
        )
    )

    profile_picture = models.URLField()

    gender = models.CharField(
        max_length=20,
        choices=(
            ('Male', 'Male'),
            ('Female', 'Female'),
            ('Do not show', 'Do not show'),
        ),
    )

PetstagramWebsite/PetstagramWebsite/pets/models.py
from django.db import models
from django.utils.text import slugify

from PetstagramWebsite.accounts.models import PetstagramUser


class Pet(models.Model):
    name = models.CharField(
        max_length=30
    )
    personal_photo = models.URLField()

    date_of_birth = models.DateField(
        blank=True,
        null=True
    )
    slug = models.SlugField(
        unique=True,
        editable=False,
        blank=True
    )
    user = models.ForeignKey(
        to=PetstagramUser,
        on_delete=models.CASCADE
    )

    def save(self, *args, **kwargs):
        # here we save and have id from DB
        super().save(*args, **kwargs)

        if not self.slug:
            self.slug = slugify(f'{self.name}-{self.id}')

        # here we update slug with existing id and save again
        return super().save(*args, **kwargs)

    def __str__(self):
        return self.name

PetstagramWebsite/PetstagramWebsite/photos/models.py
from django.db import models

from PetstagramWebsite.accounts.models import PetstagramUser
from PetstagramWebsite.pets.models import Pet
from PetstagramWebsite.photos.validators import validate_file_size
from django.core.validators import MinLengthValidator


class Photo(models.Model):
    image = models.ImageField(
        upload_to='pet_photos',
        validators=(validate_file_size,),
    )
    description = models.TextField(
        max_length=300,
        blank=True,
        null=True,
        validators=(MinLengthValidator(10),),
    )
    location = models.CharField(
        max_length=30,
        blank=True,
        null=True
    )
    tagged_pets = models.ManyToManyField(
        Pet,
        blank=True,
    )
    date_of_publication = models.DateField(
        auto_now=True
    )
    user = models.ForeignKey(
        to=PetstagramUser,
        on_delete=models.CASCADE
    )

    def __str__(self):
        pets = self.tagged_pets.all()
        names_list = [str(name) for name in pets]
        return f'{", ".join(names_list)}, ... are in this photo'

PetstagramWebsite/PetstagramWebsite/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UsernameField

from PetstagramWebsite.accounts.models import PetstagramUser


class PetstagramUserCreateForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = PetstagramUser
        fields = ['username', 'email']


class UserLoginForm(AuthenticationForm):
    username = UsernameField(
        widget=forms.TextInput(
            attrs={
                'autofocus': True,
                'placeholder': 'Username'
            }
        )
    )
    password = forms.CharField(
        strip=False,
        widget=forms.PasswordInput(
            attrs={
                'autocomplete': 'current-password',
                'placeholder': 'Password'
            }
        )
    )


class UserEditForm(forms.ModelForm):
    class Meta:
        model = PetstagramUser
        fields = ['username', 'email', 'first_name', 'last_name', 'profile_picture', 'gender']
        exclude = ['password']
        labels = {
            'username': 'Username',
            'first_name': 'First Name:',
            'last_name': 'Last Name:',
            'email': 'Email:',
            'profile_picture': 'image:',
            'gender': 'Gender:'
        }

PetstagramWebsite/PetstagramWebsite/accounts/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic as views
from django.contrib.auth import views as auth_views

from PetstagramWebsite.accounts.forms import PetstagramUserCreateForm, UserLoginForm, UserEditForm
from PetstagramWebsite.accounts.models import PetstagramUser


class UserRegisterView(views.CreateView):
    model = PetstagramUser
    form_class = PetstagramUserCreateForm
    template_name = 'accounts/register-page.html'
    success_url = reverse_lazy('login')


class UserLoginView(auth_views.LoginView):
    form_class = UserLoginForm
    template_name = 'accounts/login-page.html'
    next_page = reverse_lazy('home')


class UserLogoutView(auth_views.LogoutView):
    template_name = 'base.html'
    next_page = reverse_lazy('login')


class ProfileDetailsView(views.DetailView):
    model = PetstagramUser
    template_name = 'accounts/profile-details-page.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        total_like_count = sum(photo.like_set.count() for photo in self.object.photo_set.all())

        context['is_owner'] = self.request.user == self.object
        context['total_like_count'] = total_like_count

        return context


class ProfileEditView(views.UpdateView):
    model = PetstagramUser
    form_class = UserEditForm
    template_name = 'accounts/profile-edit-page.html'

    def get_success_url(self):
        return reverse_lazy('profile-details', kwargs={'pk': self.object.pk})


class ProfileDeleteView(views.DeleteView):
    model = PetstagramUser
    template_name = 'accounts/profile-delete-page.html'
    success_url = reverse_lazy('home')

PetstagramWebsite/templates/accounts/login-page.html
{% extends 'base.html' %}

   {% block page_content %}

    <!-- Start Login Section-->
    <div class="login-register-div">
        <div class="login-register-box">
            <h1>Petstagram</h1>

            <!-- Start Login Form-->
            <form action="{% url 'login' %}" method="post">
                {% csrf_token %}
                {{ form.username }}
                {{ form.password }}
{#                <p>#}
{#                    <label for="id_username">Username:</label>#}
{#                    <input type="text" placeholder="Username">#}
{#                </p>#}
{#                <p>#}
{#                    <label for="id_password">Password:</label>#}
{#                    <input type="password" placeholder="Password">#}
{#                </p>#}

                <!-- Login Button-->
                <button type="submit">Log in</button>
            </form>
            <!-- End Login Form -->

        </div>
        <div class="second-option">

            <!-- Link to Register Page-->
            <p>Don't have account? <a href="{% url 'register' %}">Register</a></p>
        </div>
    </div>
    <!-- End Login Section-->
    {% endblock %}

PetstagramWebsite/templates/accounts/profile-delete-page.html
{% extends 'base.html' %}
{% load static %}

   {% block page_content %}

    <!-- Start Delete Profile Section -->
        <div class="delete-profile">
            <h1>
                Are you sure you want to delete your profile?
            </h1>

            <form method="post" action="{% url 'profile-delete' object.pk %}">
                {% csrf_token %}
                <div class="sure-buttons">
                <!-- Yes (Delete Profile) Button -->
                    <button>Yes</button>
                <!-- Go Back Button -->
                    <a class="edit-btn" href="javascript:history.back()">Go Back</a>
                </div>
            </form>
            <img src="{% static 'images/are_you_sure_cat.gif' %}" alt="are you sure cat git">
        </div>
    <!-- End Delete Profile Section -->

   {% endblock %}

PetstagramWebsite/templates/accounts/profile-details-page.html
{% extends 'base.html' %}
{% load static %}

   {% block page_content %}

    <!-- Start Profile Details Section -->
    <div class="profile">

        <!-- Start Profile Personal Data Section -->
        <div class="profile-data">
            <div class="profile_img">
                <div class="image">

                    {% if not object.profile_picture %}
                    <img src="{% static 'images/person.png' %}" alt="img8">
                    {% else %}
                       <img src="{{ object.profile_picture }}" alt="img8">
                    {% endif %}
                </div>
            </div>
            <div class="personal">
                <div class="edit">
                    <!-- User Username -->
                    <p>{{ object.username }}</p>
                     {% if is_owner %}
                    <!-- IF the viewer is the owner of the profile -->
                    <!-- Link to Edit Profile Page -->
                    <a href="{% url 'profile-edit' object.pk %}">
                        <img class="edit-img" src="{% static 'images/edit-pen-icon-6.jpg' %}" alt="edit button">
                    </a>

                    <!-- Link to Delete Profile Page -->
                    <a href="{% url 'profile-delete' object.pk %}">
                        <img class="bin-img" src="{% static 'images/icon-remove-22.jpg' %}" alt="bin button">
                    </a>
                    <!-- End IF the viewer is the owner of the profile -->
                    {% endif %}
                </div>
                <div class="data">

                    <!-- Total Number of Photos by the User -->
                    <span>{{ object.photo_set.count }}</span>
                    <p>photos</p>

                    <!-- Total Number of Pets owned by the User -->
                    <span>{{ object.pet_set.count }}</span>
                    <p>pets</p>

                    <!-- Total Number of Likes for the User -->
                    <span>{{ total_like_count }}</span>
                    <p>likes</p>
                </div>
                {% if object.get_full_name %}
                <h3 class="names">{{ object.get_full_name }}</h3>
               {% endif %}

                <!-- User Email Address -->
                <p class="email">{{ object.email }}</p>

                <!-- User Gender IF Added -->
                <p class="gender">{{ object.gender }}</p>
            </div>
        </div>
        <!-- End Profile Personal Data Section -->

        <!-- Start Pets Data Section -->
        <div class="pets">
            <div class="statuses">
            {% for pet in object.pet_set.all %}
                <!-- Start 1st Pet Details Page -->
                <!-- Link to First Pet Details Page -->
                <a href="{% url 'pet_details' object.username pet.slug %}">
                    <div class="head-pet">
                        <div class="status">
                            <div class="image">
                                <!-- Pet Image -->
                                <img src="{{ pet.personal_photo }}"
                                     alt="pet img">
                            </div>
                        </div>
                        <!-- Pet Name -->
                        <p>{{ pet.name }}</p>
                    </div>
                </a>
                <!-- End 1st Pet Details Page -->
            {% endfor %}

            </div>
        </div>
        <!-- End Pets Data Section -->

        <!-- Start Last Uploaded Photos Section -->
        <div class="pet-photos">

            <!-- Link to Last Uploaded Pet Photo -->
            {% for photo in object.photo_set.all %}
            <a href="{% url 'photo_details' photo.pk%}">
                <!-- Pet Photo -->
                <img src="/media/{{ photo.image }}" alt="pet img">
            </a>
            {% endfor %}

        </div>
        <!-- End Last Uploaded Photos Section -->

    </div>
    <!-- End Profile Details Section -->

    {% endblock %}

PetstagramWebsite/templates/accounts/profile-edit-page.html
{% extends 'base.html' %}

   {% block page_content %}
    <!-- Start Edit Profile Section -->
    <div class="edit-delete">
        <h2>Edit Profile</h2>
        <!-- Start Edit Profile From -->
        <form action="" method="post">
{#        <form action="{% url 'profile-edit' request.user.pk %}" method="post">#}
            {% for field in form %}
            <p class="error">{{ field.errors }}</p>
            <div class="label-input">
                <label>{{ field.label }}</label>
                {% if not field.label == 'Gender:' %}
                    {{ field }}
                {% else %}
                <div class="list-choice">
                    <div class="list-choice-title">Gender</div>
                    <div class="list-choice-objects">
                        {% for type, value in form.fields.gender.choices %}
                        <label>
                            <input type="radio" value="{{ value }}" name="gender"
                            {% if form.value == value %}
                                   checked
                            {% endif %}/>
                            <span>{{ value }}</span>
                        </label>
                        {% endfor %}
                    </div>
                </div>
                {% endif %}
            </div>
            <br>
            {% endfor %}
            {% csrf_token %}
            <!-- Edit Profile Button -->
            <button class="edit-btn" type="submit">Edit</button>
        </form>
        <!-- End Edit Profile Form -->

    </div>
    <!-- End Edit Profile Section -->

    {% endblock %}

PetstagramWebsite/templates/accounts/register-page.html
{% extends 'base.html' %}
{% load custom_filters %}
   {% block page_content %}
    <!-- Start Register Section -->
    <div class="login-register-div">
        <div class="login-register-box">
            <h1>Petstagram</h1>

            <!-- Start Register Form -->
            <form action="{% url 'register' %}" method="post">
                {{ form.username.errors }}
                {{ form.username | placeholder:'Username'}}
                {{ form.email.errors }}
                {{ form.email | placeholder:'Email' }}
                {{ form.password1.errors }}
                {{ form.password2.errors }}
                {{ form.password1 | placeholder:'Passowrd'}}
                {{ form.password2 | placeholder:'Repeat password'}}
                {% csrf_token %}

                <!-- Register Button -->
                <button type="submit">Register</button>
            </form>
            <!-- End Register Form -->

        </div>
        <div class="second-option">

            <!-- Link to Login Page -->
            <p>Have an account? <a href="{% url 'login' %}">Log in</a></p>
        </div>
    </div>
    <!-- End Register Section -->
    {% endblock %}